{% set name = "forestci" %}
{% set version = "0.4.1" %}
{% set sha256 = "e8a7b059476dd6871aba2d049c1f9b3ed16c75e92c9d5982cef1cdd551e0595b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python
    - setuptools
    - numpy
    - scipy
  run:
    - python
    - scikit-learn
    - numpy
    - scipy

test:
  imports:
    - forestci

about:
  home: https://github.com/scikit-learn-contrib/forest-confidence-interval
  license: MIT
  # The LICENSE.txt file is not in the MANIFEST.in, so this will fail when trying to build from the pypi tarball since it won't be there. 
  # Comment out license_file line and add it once theMANIFEST.in has been patched upstream.
  #license_file: LICENSE.txt
  summary: calculate confidence intervals for scikit-learn random forest regression or classification objects

  description: |
    a Python module for calculating variance and adding confidence intervals to scikit-learn
    random forest regression or classification objects. The core functions calculate an in-bag and 
    error bars for random forest objects
  doc_url: http://contrib.scikit-learn.org/forest-confidence-interval/
  dev_url: https://github.com/scikit-learn-contrib/forest-confidence-interval

extra:
  recipe-maintainers:
    - arokem
    - kpolimis
