travis:
  secure:
    BINSTAR_TOKEN: kUfizB/AUUZ8HljIKwXc6cPSGgA054gNxcFROIgfWtMnhK2TosqXUIDP9ij0V6+7fTdAymhHPY1q12u2v0tvCeRJs6X3SIqMzJc9eWOwEh4ThQCrLJ6VMcAUjR1xmr5ZjXtcUwNqFHKVp8PzHbJPfhDuGOeXV1g/xOw6yk4B9l/tQwOaZw/BEcosAY5fkvoV5OhQ+rxc22A9f1fXXyOLT8vz0UDdXvEXIS2ondOyvuN7rswjozSzSqPWHC4x02nB9bXa8ugf6fPyOldjTSeDbuOnAArFYpzvQNolCl9b9GC86YCHZcB+CugqpPJ/QzVPdNNFJTcjyxXLHyA+AH0g6evQU0+jxs5C0BF9MlzdY7mj5d9K8ctUt43eLIG+g490ww+AE9pM3J70Kpx+vgg0QeT1Uu5TghFfn7QorHnkPnnh2hvZo2d0TeGtxeJPFzbCP7OdJIlVNBjcO1eIWLx/P5e9LGvs9aZp0U08eyu27ZIPTy8cAgtORZaeknqe5VAzx81sF0m1tPUyZkPt3VspwdzX9so4/Nq20LqvBEt49acjOfj2yfuVG7xHG5QEnLPhbEheQQquj6ZmpP0O8X6B7ilv6XQ6BerLZMW4YaKuzJJah/h6ttxSK7vatkyFhUWNoaHBpvyOoks0YOHWnTwIXAo/6fW+mkl5CDykFYJ7GEQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
