travis:
  secure:
    BINSTAR_TOKEN: SBHcSPR1pT2icQI/PPIiW3C0dZ/Whzk/zykDIczmR2vM+7sP04sPZ3cmDYextwr3nJNitmFbMqbQ7E4tqwUFHaVfZXKp4yq5U7TvsVUCvl62opIRlsEK/T+zEm78potdvDEzir9RGN+iuz1fZpXzCXSdOrLfLUO7Hxk7WNx2JCF7wxOmmNEfFr/0m/LrOflxx3y6AMUkKJp3NL/C5Pb7Xg3dlfNFWt3BXOLifzZUxaGq0msKiktKoIY/t7DP045gD2KPFKzxkdIgR6JY0otyW+Ha+5Cy+RN8aZARWuP2J6QostRKjc2MHklYlye3cacoe/Dh35fvU3Xu6DwJYMSfb6GS6qeHipKApbI+qD6nnOP92mIHptO3MkMrsILUhmhglsbhrRovAGCpE4RvYeEQ/qJ1OTZ5cR2iu07jH48acC5MtgAJmTgmWic/2hEB/Iq1ri5rG/GBtWcXOBsZDHsMvoZAFfPLVLB2n8rvi72gH6fr8K0LHNj4VS0u3mfpB2g6WV14RiuxzgDLsELRfDEoVd3mo0CB55CkQzQ3IsVfYeZfJttn/2fxumrxfd3feDBL6UDpS2uR3ooYviV4vzVjmUXDGhLu6unxK5PsipI5pRwDl9JngPD8vqkbZeCXK40lphWbnzAusvf3bFrLUKxfcNh3Ka7PkoLrTwsGwLKyGbw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
